//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDUOCPHAM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=\". \\THANHNHA\";Initial Catalog=QLBH_CS_NHA_NGOC;Integrated Security=Tr" +
            "ue")]
        public string CS_N12_5601_QLBH_GIAYConnectionString {
            get {
                return ((string)(this["CS_N12_5601_QLBH_GIAYConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THANHNHA\\SQL_TN;Initial Catalog=QLBH_CS_NHA_NGOC;Integrated Security=" +
            "True")]
        public string CS_N12_5601_QLBH_GIAYConnectionString1 {
            get {
                return ((string)(this["CS_N12_5601_QLBH_GIAYConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THANHNHA\\SQL09;Initial Catalog=QLBH_CS_NHA_NGOC;Persist Security Info" +
            "=True;User ID=sa;Password=1234567")]
        public string QLBH_CS_NHA_NGOCConnectionString {
            get {
                return ((string)(this["QLBH_CS_NHA_NGOCConnectionString"]));
            }
        }
    }
}
